# Используем build как базовый образ
FROM build AS runtime

WORKDIR /app

# Копируем собранное приложение
COPY --from=build /app/dist /app
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/server.js /app/server.js

# Запускаем контейнер от непривилегированного пользователя
USER appuser

EXPOSE ${PORT}

CMD ["node", "server.js"]

