# Используем минимальный Node.js образ
FROM node:18-alpine AS runtime

# Создаем непривилегированного пользователя
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем собранный проект из build
COPY --from=build /app/dist /app
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/server.js /app/server.js

# Переключаемся на пользователя
USER appuser

# Запуск приложения
CMD ["node", "/app/server.js"]

